server {
    listen 80;
    server_name yourname.com www.yourname.com;

    root /sites/portfolio;
    index index.html;

    location / {
        try_files $uri $uri/ $uri.html =404;
    }

    error_page 404 /404.html;
}