services:
  app_api_blue:
    image: registry.yourname.com/app-api:${BLUE_VERSION:-latest}
    restart: unless-stopped
    env_file:
      - .env
      - /home/pi/releases/dynamic/app/api/blue.env
    volumes:
      - /home/pi/data/uploads/app:/uploads
    networks:
      - web

  app_api_green:
    image: registry.yourname.com/app-api:${GREEN_VERSION:-latest}
    restart: unless-stopped
    env_file:
      - .env
      - /home/pi/releases/dynamic/app/api/green.env
    volumes:
      - /home/pi/data/uploads/app:/uploads
    networks:
      - web

networks:
  web:
    name: web
    external: true